// Punto único de importación de los esquemas/tipos del dominio.
// Importar con el alias de rootDir: `~~/schemas` (o `@@/schemas`).
export * from './common'
export * from './service'
export * from './barber'
export * from './appointment'
export * from './waitlist'
export * from './client'
export * from './review'
export * from './settings'
export * from './image'
export * from './alert'
export * from './notification'
export * from './fixed'
export * from './loyalty'
export * from './expense'
export * from './product'
export * from './barberInvite'
